### ISSUE TITLE
راهی جهت ارتباط

### ISSUE THREAD

**Issue by zoghal** [bijanebrahimi/unicode-presentation#1]
درود بر شما 
من دنبال ایجاد یک اسلاید برای نمایش در خانه فونت بودم. که با اسلاید کامل شما  برخوردم.
ممنون میشم با من ارتباط برقرار کنید تا در این باره با شما صحبتی داشته باشم.
ایمیل من saleh.souzanchi@gmail.com

**Comment by bijanebrahimi** [comment]
‫@zoghal با سلام و عرض پوزش بابت تاخیر
‫متاسفانه من هم‌اکنون در حال سپری کردن خدمت سربازی هستم :دی و بجز مرخصی‌های کوتاه مدت وقتی برای رسیدن به اینگونه فعالیت‌ها برام باقی نمی‌مونه :( بهرحال ازونجایی که مقاله‌تون رو تو مجله سلام‌دنیا چند وقت پیش خوندم فکر می‌کنم جواب سوال‌هاتون رو گرفته باشید.

---

با آرزوی موفقیت
dev-null at riseup dot net

**Comment by zoghal** [comment]
درود بر شما. امیدوارم سربازیتون زود زود تموم بشه.
راستش من دنبال سوالی نبودم. بیشتر میخواستم اجازه بگیرم این اسلاید رو کمی تغییر بدم و در پروژه خانه فونت قرار بدم. و اگر ممکنه سورس رو داشته باشم تا تغییرات رو اعمال کنم.
ممنون میشم تا هستید این اعلام کنید ایا این اجازه رو می دید به من یا خیر. 
ممنون

**Comment by bijanebrahimi** [comment]
@zoghal 
‫اوه! اسلاید‌ها با مجوز [GPLv3.0](https://raw.githubusercontent.com/bijanebrahimi/unicode-presentation/master/LICENSE) منتشر شدن (لایسنس بدی برای اسلاید بود. می‌دونم) بهرحال تا زمانی که به لایسنس پایبند باشید هیچ مشکلی نخواهد بود. که شامل هر گونه تغییر و استفاده ازون به نام خودتون (البته با حفظ لایسنس)

‫سورس اسلاید با فرمت آزاد (odp) تو گیت‌هاب هست که با libreoffice ایجاد شده. این ارائه رو من یکسال پیش حدودا تو [جلسه باز نرم‌افزاری مشهد](http://www.mashhadsoftwaretalks.ir) ارائه کردم. اونجا دوستان از ارائه فیلم هم گرفتن که [اینجا](https://www.dropbox.com/s/npydmohhfaj5pvj/presentation_unicode.webm?dl=0) می‌تونید ببینیدش:

Video: https://www.dropbox.com/s/npydmohhfaj5pvj/presentation_unicode.webm?dl=0

**Comment by zoghal** [comment]
ممنون اگر فیلم داره که داره منظورم قابل قبول برای ارایه باشه همون فیلم رو قرار میدیم که همه چیز رعایت شده باشه 
در کل سپاسگذارم.

**Comment by bijanebrahimi** [comment]
‫‫اصراری نیست. فیلم رو تنها برای توضیحات صفحات اسلاید اضافه کردم :) فقط مایلم در صورتی که کاری در این مورد انجام دادین من رو هم مطلع بکنید

**Comment by zoghal** [comment]
کیفیت صداش مناسب نیست. بطور کلی هدف اینه که کار گروهی باشه. و در همین راستا هم سعی میکنم اندکی تغییرات روی اسلاید اعمال کنم و با اسم خودتون ارائه بشه.البته اگر در دسترس بودین از خودتون می خواستم اصلاح کنید. که میگید سرباز وطن هستید. 
نتیجه هم اینجا قرار میگیره font-store.ir . چون ممکنه فراموش کنم اطلاع رسانی کنم این مورد هم به عهده خودتون میزارم. انشالله بعد از ۲۲ بهمن استاترش رو میزنیم.
